{% set name = "bertha" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/cph-tum/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 740341ed525f03c27e5879c633c4b51398b0d95f31a9465bc539d3c0c34f5352

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make             # [unix]
    - ninja            # [win]
    - swig
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - make             # [unix]
    - ninja            # [win]
  files:
    - export_test/CMakeLists.txt
    - export_test/cmake_export_test.cpp
  commands:
    - python -c "import bertha.core as b; d = b.device(1, 2); d.get_length()"
    - mkdir -p build && cd build
    - cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../export_test     # [win]
    - cmake --build . --config Release                               # [win]
    - cmake_export_test                                              # [win]
    - cmake -DCMAKE_BUILD_TYPE=Release ../export_test                # [unix]
    - cmake --build .                                                # [unix]
    - ./cmake_export_test                                            # [unix]

about:
  home: https://gitlab.com/cph-tum/bertha
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Project skeleton for scientific C++ software w/ Python interface.'
  description: |
      bertha is a light-weight project skeleton for scientific software
      libraries written in C++ (featuring a Python interface).
  doc_url: https://cph-tum.gitlab.io/bertha
  dev_url: https://gitlab.com/cph-tum/bertha

extra:
  recipe-maintainers:
    - mriesch-tum
